-- Chapter 3. Restricting and Sorting Data

SELECT PRODUCT_NAME, LIST_PRICE
FROM PRODUCT_INFORMATION
WHERE (PRODUCT_NAME LIKE 'HD%' AND LIST_PRICE BETWEEN 500 AND 800) OR
(PRODUCT_NAME LIKE 'GP%1024%')
ORDER BY LIST_PRICE DESC;